### ISSUE TITLE
Add automatic exception handling

### ISSUE THREAD

**Issue by nickroberts** [angulartics/angulartics-segment#19]
It would be nice if we could have automatic exception tracking, like the GA and GTM plugins.

**Comment by nickroberts** [comment]
Added PR #18 to address this.

**Comment by timelf123** [comment]
Good contribution thanks

**Comment by nickroberts** [comment]
Any way we can get a new release / tag? If not, no biggie (for now). Thanks!

**Comment by timelf123** [comment]
Incoming, it's now on my todo list for the next few days
