### ISSUE TITLE
I'd like to join as a maintainer

### ISSUE THREAD

**Issue by flinn** [angulartics/angulartics-segment#5]
Hey! 

I'm setting angulartics-segment up for an AngularJS application that I've been working on, so I'm interested in joining as a maintainer for this repo if one is still needed :)

Best,
Matt

**Comment by ProLoser** [comment]
Hey @flinn sorry for not seeing this sooner (I get way too many notifications). I've added you to the team, but please take careful reservation with any major API / behavioral changes you make.
