### ISSUE TITLE
Pass element text as property to event

### ISSUE THREAD

**Issue by troex** [angulartics/angulartics-segment#9]
I'm trying to implement [Clicked CTA](https://help.segment.com/hc/en-us/articles/205512365-Button-clicks-links-or-call-to-actions-tracking), my current code looks like this:

``` html
<a
  class="btn" href="..."
  analytics-on
  analytics-event="Clicked CTA"
  analytics-cta="Sign Up"
  analytics-type="Button"
  analytics-text="Start 14 Days Trial">Start 14 Days Trial</a>
```

Is there a way to automatically pass `analytics-text` based on current element text, to avoid duplication?

**Comment by ProLoser** [comment]
@troex I would open this issue in angulartics/angulartics repo, as I've been interested in the same thing.

**Comment by troex** [comment]
moved to https://github.com/angulartics/angulartics/issues/478
